#!/usr/bin/env bash
#Script that install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Port 80
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.html
sudo /etc/init.d/nginx start # service and systemctl
