#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 4555-lb-01
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 4555-web-01 23.20.75.80 check
        server 4555-web-02 54.83.87.163 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart