#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

h=0
m=0
while [ $h -le 12 ] # less or equal - Hour 
do
    m=1
    echo "Hour: $h"
    while [ $m -lt 60 ] # less than - minutes
    do
        echo $m
	((m++))
    done
    ((h++))
done
